# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nakshrathore/programming/cpp/Glitter

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nakshrathore/programming/cpp/Glitter

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\" \"assimp-dev\" \"libassimp5.4.3-dev\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nakshrathore/programming/cpp/Glitter/CMakeFiles /home/nakshrathore/programming/cpp/Glitter//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nakshrathore/programming/cpp/Glitter/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Glitter

# Build rule for target.
Glitter: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 Glitter
.PHONY : Glitter

# fast build rule for target.
Glitter/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/build
.PHONY : Glitter/fast

#=============================================================================
# Target rules for targets named uninstall

# Build rule for target.
uninstall: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 uninstall
.PHONY : uninstall

# fast build rule for target.
uninstall/fast:
	$(MAKE) $(MAKESILENT) -f Glitter/Vendor/glfw/CMakeFiles/uninstall.dir/build.make Glitter/Vendor/glfw/CMakeFiles/uninstall.dir/build
.PHONY : uninstall/fast

#=============================================================================
# Target rules for targets named glfw

# Build rule for target.
glfw: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 glfw
.PHONY : glfw

# fast build rule for target.
glfw/fast:
	$(MAKE) $(MAKESILENT) -f Glitter/Vendor/glfw/src/CMakeFiles/glfw.dir/build.make Glitter/Vendor/glfw/src/CMakeFiles/glfw.dir/build
.PHONY : glfw/fast

#=============================================================================
# Target rules for targets named update_mappings

# Build rule for target.
update_mappings: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 update_mappings
.PHONY : update_mappings

# fast build rule for target.
update_mappings/fast:
	$(MAKE) $(MAKESILENT) -f Glitter/Vendor/glfw/src/CMakeFiles/update_mappings.dir/build.make Glitter/Vendor/glfw/src/CMakeFiles/update_mappings.dir/build
.PHONY : update_mappings/fast

#=============================================================================
# Target rules for targets named assimp

# Build rule for target.
assimp: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 assimp
.PHONY : assimp

# fast build rule for target.
assimp/fast:
	$(MAKE) $(MAKESILENT) -f Glitter/Vendor/assimp/code/CMakeFiles/assimp.dir/build.make Glitter/Vendor/assimp/code/CMakeFiles/assimp.dir/build
.PHONY : assimp/fast

Glitter/Sources/camera.o: Glitter/Sources/camera.cpp.o
.PHONY : Glitter/Sources/camera.o

# target to build an object file
Glitter/Sources/camera.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/camera.cpp.o
.PHONY : Glitter/Sources/camera.cpp.o

Glitter/Sources/camera.i: Glitter/Sources/camera.cpp.i
.PHONY : Glitter/Sources/camera.i

# target to preprocess a source file
Glitter/Sources/camera.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/camera.cpp.i
.PHONY : Glitter/Sources/camera.cpp.i

Glitter/Sources/camera.s: Glitter/Sources/camera.cpp.s
.PHONY : Glitter/Sources/camera.s

# target to generate assembly for a file
Glitter/Sources/camera.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/camera.cpp.s
.PHONY : Glitter/Sources/camera.cpp.s

Glitter/Sources/main.o: Glitter/Sources/main.cpp.o
.PHONY : Glitter/Sources/main.o

# target to build an object file
Glitter/Sources/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/main.cpp.o
.PHONY : Glitter/Sources/main.cpp.o

Glitter/Sources/main.i: Glitter/Sources/main.cpp.i
.PHONY : Glitter/Sources/main.i

# target to preprocess a source file
Glitter/Sources/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/main.cpp.i
.PHONY : Glitter/Sources/main.cpp.i

Glitter/Sources/main.s: Glitter/Sources/main.cpp.s
.PHONY : Glitter/Sources/main.s

# target to generate assembly for a file
Glitter/Sources/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/main.cpp.s
.PHONY : Glitter/Sources/main.cpp.s

Glitter/Sources/mesh.o: Glitter/Sources/mesh.cpp.o
.PHONY : Glitter/Sources/mesh.o

# target to build an object file
Glitter/Sources/mesh.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/mesh.cpp.o
.PHONY : Glitter/Sources/mesh.cpp.o

Glitter/Sources/mesh.i: Glitter/Sources/mesh.cpp.i
.PHONY : Glitter/Sources/mesh.i

# target to preprocess a source file
Glitter/Sources/mesh.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/mesh.cpp.i
.PHONY : Glitter/Sources/mesh.cpp.i

Glitter/Sources/mesh.s: Glitter/Sources/mesh.cpp.s
.PHONY : Glitter/Sources/mesh.s

# target to generate assembly for a file
Glitter/Sources/mesh.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/mesh.cpp.s
.PHONY : Glitter/Sources/mesh.cpp.s

Glitter/Sources/model.o: Glitter/Sources/model.cpp.o
.PHONY : Glitter/Sources/model.o

# target to build an object file
Glitter/Sources/model.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/model.cpp.o
.PHONY : Glitter/Sources/model.cpp.o

Glitter/Sources/model.i: Glitter/Sources/model.cpp.i
.PHONY : Glitter/Sources/model.i

# target to preprocess a source file
Glitter/Sources/model.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/model.cpp.i
.PHONY : Glitter/Sources/model.cpp.i

Glitter/Sources/model.s: Glitter/Sources/model.cpp.s
.PHONY : Glitter/Sources/model.s

# target to generate assembly for a file
Glitter/Sources/model.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/model.cpp.s
.PHONY : Glitter/Sources/model.cpp.s

Glitter/Sources/shader.o: Glitter/Sources/shader.cpp.o
.PHONY : Glitter/Sources/shader.o

# target to build an object file
Glitter/Sources/shader.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/shader.cpp.o
.PHONY : Glitter/Sources/shader.cpp.o

Glitter/Sources/shader.i: Glitter/Sources/shader.cpp.i
.PHONY : Glitter/Sources/shader.i

# target to preprocess a source file
Glitter/Sources/shader.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/shader.cpp.i
.PHONY : Glitter/Sources/shader.cpp.i

Glitter/Sources/shader.s: Glitter/Sources/shader.cpp.s
.PHONY : Glitter/Sources/shader.s

# target to generate assembly for a file
Glitter/Sources/shader.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/shader.cpp.s
.PHONY : Glitter/Sources/shader.cpp.s

Glitter/Sources/stb_image.o: Glitter/Sources/stb_image.cpp.o
.PHONY : Glitter/Sources/stb_image.o

# target to build an object file
Glitter/Sources/stb_image.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/stb_image.cpp.o
.PHONY : Glitter/Sources/stb_image.cpp.o

Glitter/Sources/stb_image.i: Glitter/Sources/stb_image.cpp.i
.PHONY : Glitter/Sources/stb_image.i

# target to preprocess a source file
Glitter/Sources/stb_image.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/stb_image.cpp.i
.PHONY : Glitter/Sources/stb_image.cpp.i

Glitter/Sources/stb_image.s: Glitter/Sources/stb_image.cpp.s
.PHONY : Glitter/Sources/stb_image.s

# target to generate assembly for a file
Glitter/Sources/stb_image.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/stb_image.cpp.s
.PHONY : Glitter/Sources/stb_image.cpp.s

Glitter/Sources/texture.o: Glitter/Sources/texture.cpp.o
.PHONY : Glitter/Sources/texture.o

# target to build an object file
Glitter/Sources/texture.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/texture.cpp.o
.PHONY : Glitter/Sources/texture.cpp.o

Glitter/Sources/texture.i: Glitter/Sources/texture.cpp.i
.PHONY : Glitter/Sources/texture.i

# target to preprocess a source file
Glitter/Sources/texture.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/texture.cpp.i
.PHONY : Glitter/Sources/texture.cpp.i

Glitter/Sources/texture.s: Glitter/Sources/texture.cpp.s
.PHONY : Glitter/Sources/texture.s

# target to generate assembly for a file
Glitter/Sources/texture.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Sources/texture.cpp.s
.PHONY : Glitter/Sources/texture.cpp.s

Glitter/Vendor/glad/src/glad.o: Glitter/Vendor/glad/src/glad.c.o
.PHONY : Glitter/Vendor/glad/src/glad.o

# target to build an object file
Glitter/Vendor/glad/src/glad.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Vendor/glad/src/glad.c.o
.PHONY : Glitter/Vendor/glad/src/glad.c.o

Glitter/Vendor/glad/src/glad.i: Glitter/Vendor/glad/src/glad.c.i
.PHONY : Glitter/Vendor/glad/src/glad.i

# target to preprocess a source file
Glitter/Vendor/glad/src/glad.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Vendor/glad/src/glad.c.i
.PHONY : Glitter/Vendor/glad/src/glad.c.i

Glitter/Vendor/glad/src/glad.s: Glitter/Vendor/glad/src/glad.c.s
.PHONY : Glitter/Vendor/glad/src/glad.s

# target to generate assembly for a file
Glitter/Vendor/glad/src/glad.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Glitter.dir/build.make CMakeFiles/Glitter.dir/Glitter/Vendor/glad/src/glad.c.s
.PHONY : Glitter/Vendor/glad/src/glad.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... uninstall"
	@echo "... update_mappings"
	@echo "... Glitter"
	@echo "... assimp"
	@echo "... glfw"
	@echo "... Glitter/Sources/camera.o"
	@echo "... Glitter/Sources/camera.i"
	@echo "... Glitter/Sources/camera.s"
	@echo "... Glitter/Sources/main.o"
	@echo "... Glitter/Sources/main.i"
	@echo "... Glitter/Sources/main.s"
	@echo "... Glitter/Sources/mesh.o"
	@echo "... Glitter/Sources/mesh.i"
	@echo "... Glitter/Sources/mesh.s"
	@echo "... Glitter/Sources/model.o"
	@echo "... Glitter/Sources/model.i"
	@echo "... Glitter/Sources/model.s"
	@echo "... Glitter/Sources/shader.o"
	@echo "... Glitter/Sources/shader.i"
	@echo "... Glitter/Sources/shader.s"
	@echo "... Glitter/Sources/stb_image.o"
	@echo "... Glitter/Sources/stb_image.i"
	@echo "... Glitter/Sources/stb_image.s"
	@echo "... Glitter/Sources/texture.o"
	@echo "... Glitter/Sources/texture.i"
	@echo "... Glitter/Sources/texture.s"
	@echo "... Glitter/Vendor/glad/src/glad.o"
	@echo "... Glitter/Vendor/glad/src/glad.i"
	@echo "... Glitter/Vendor/glad/src/glad.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

